version: "3.8"
services:
  postgresDB:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=Newpostgres
      - POSTGRES_PASSWORD=Newpostgres
      - POSTGRES_DB=postgresDB-3
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5435:5432"